# This file uses the following environment variables set within the build workflow:
# - SITE_URL: the URL of the site (Falls back to a default URL)
# For example, for PR-previews, SITE_URL is set to <default_URL>/pr-previews/pr-NUM

site_name: Config docs

# Site URL
site_url: !ENV [READTHEDOCS_CANONICAL_URL, "https://docs.access-hive.org.au/latest/"]
# Git repository (Adds a link to the GitHub repository at the top)
repo_url: https://github.com/ACCESS-NRI/access-hive.org.au
repo_name: access-hive.org.au

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: custom-light
      primary: none
      accent: none
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: none
      accent: none
      scheme: custom-dark
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

  features:
    # - navigation.top
    # - navigation.instant
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.indexes
    # - navigation.footer
    # - navigation.tracking       # The URL in the address bar is automatically updated with active anchor
    - content.code.copy         # for displaying copy icon at top right in code snippets  
    - content.code.annotate
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
    # - toc.follow                # the sidebar is automatically scrolled to the active anchor

  logo: assets/ACCESS_icon_HIVE.png
  favicon: assets/ACCESS_icon_HIVE.png
  icon:
    edit: material/pencil
    view: material/eye
copyright: Copyright &copy; 2025 ACCESS-NRI

plugins:
  - git-revision-date-localized:
      type: date
      enable_creation_date: false
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - bibtex:
      bib_file: "references.bib"
  - events:
      events_dir: community_resources/events/events
  - resolve-absolute-urls
  - macros

# Extensions
markdown_extensions: 
  - attr_list
  - abbr
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - footnotes
  - tables
  - toc:
      title: On this page

# Footer
extra:
  generator: false
  social:
    - icon: fontawesome/brands/bluesky 
      link: https://bsky.app/profile/access-nri.bsky.social
      name: ACCESS-NRI on Bluesky
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/access-nri
      name: ACCESS-NRI on Linkedin
  # analytics:
  #   provider: google
  #   property: G-2T6SQEH2CX
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/emoticon-happy-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/emoticon-sad-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >- 
  #           Thanks for your feedback!<br>
  #           Help us improve this page by <a href=/about/contribute target="_blank" rel="noopener">contributing</a>!

extra_css:
  - "https://fonts.googleapis.com/icon?family=Material+Icons"   # Material Icons Reference - https://material.io/resources/icons/?style=baseline
  - fontawesome-free-6.4.0-web/css/all.css
  - fontello/css/fontello-codes.css
  - fontello/css/fontello-ie7-codes.css
  - fontello/css/fontello-ie7.css
  - fontello/css/fontello.css
  - css/access-nri.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # For pymdownx.arithmatex extension
  - https://cdn.jsdelivr.net/gh/atteggiani/animated-terminal@3.0/animated-terminal.min.js # Terminal animations
  - js/custom-tags.js
  - js/miscellaneous.js

# Automatically reload page when running `mkdocs serve`, for any 
# of the following files outside of the 'docs' directory
watch:
  - mkdocs.yml
  - overrides/